'use client';
// TODO: Remove this useClient by trying to synchronize front builder with server builder
import { BOB } from '../bob/bobInstance';
import './global.css';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import dynamic from 'next/dynamic';

BOB.init('example-of-api-key');

const ProductTile = dynamic(
  async () => (await import('../components/ProductTile/ProductTile')).default
);

BOB.registerComponent('testProductTile', ProductTile, [
  { name: 'title', type: 'string' },
  {
    name: 'productData',
    type: 'object',
    subfields: [
      {
        name: 'name',
        type: 'string',
      },
      {
        name: 'count',
        type: 'number',
      },
    ],
  },
]);

BOB.registerComponent('anotherProductTile', ProductTile, [
  { name: 'title', type: 'string' },
]);

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
